### ISSUE TITLE
User can search characters

### ISSUE THREAD

**Issue by addy-abid** [addy-abid/ajax-project-first#1]
## Functionality

Users are able to search characters from the TV show, 'Rick and Morty'.

## 🖼️ Wireframes

![Screen Shot 2021-09-21 at 5 54 31 PM](https://user-images.githubusercontent.com/85080021/134266773-51455842-a7d2-405d-a4f3-0465d81ed100.png)

## ✅ Task List

- [x] Add HTML header
- [x] Create form for search entries
- [x] create "data-view" for home page
- [x] Add input field for search bar
- [x] Add button to initiate the search
- [x] Add background image to container
- [x] Add any other images
- [x] Add any other necessary CSS styling
- [x] Create data model in JS 
- [x] Add the current view to the data model
