### ISSUE TITLE
User can view character details

### ISSUE THREAD

**Issue by addy-abid** [addy-abid/ajax-project-first#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

Users are able to view specific details about their favorite characters!

## 🖼️ Wireframes

![Screen Shot 2021-09-27 at 8 35 35 PM](https://user-images.githubusercontent.com/85080021/135019121-88b614a9-e034-4225-8872-9769ff750806.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

 - [x] - Create new view for character info card in HTML
 - [x] - Add styling to fit both mobile and desktop screens
 - [x] - Create new dom tree and append it to the page for when a user clicks on a character
 - [x] - Hide any other view besides the character info card
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
